### ISSUE TITLE
igMaskEditor is not reverted to last valid value

### ISSUE THREAD

**Issue by dafo** [IgniteUI/ignite-ui#48] opened 2016-07-04 12:34 UTC
**Steps to reproduce:**
1. Initialize mask editor, using the following code:
```
$("#maskEditor1").igMaskEditor({
  inputMask : "9900",
  revertIfNotValid: true
});
```

2. Enter '1234'
3. Click outside the editor to blur the editor
4. Focus the editor again and delete the last digit (Value should be 123_)
5. Blur the editor again

**Actual result:** 
The value is not reverted to the last valid one ('1234').  Only notification is shown - 'All required positions should be filled'

**Expected result:**
The value should be reverted.

**Comment by kdinev** [comment] 2016-07-20 14:14
@ig-ealbert this issue contains changes to localization files. Assigning to you for translation.

**Comment by kdinev** [comment] 2016-07-21 14:47
@ig-ealbert Should I close the issue, or there is more to be done here? Btw, you can associate the pull request with the issue by using pound sign and number of the issue in the title or comment. :)

**Comment by ig-ealbert** [comment] 2016-07-21 14:53
@kdinev I think it's safe to close this issue.  As I mentioned in the email, we need to outsource the other locales closer to code freeze and we should discuss when to do that.  But that doesn't have to be related to this issue and it can be closed.
Thanks for the tip about associating the pull request with an issue!

**Comment by kdinev** [comment] 2016-07-21 15:07
@ig-ealbert If you want, we can keep the issue open and tag it for translation and close it once the translated strings are also added?
Another tip is that you can add in the title or description of the pull request "closes" and reference the issue. Then when the pull request is merged the issue is automatically closed!

**Comment by ig-ealbert** [comment] 2016-07-21 15:09
@kdinev I'd prefer is we closed this issue and perhaps opened a new one for the other locale translations, like a general one for the release.  We have a task in TFS.  How would you like to handle this?

**Comment by kdinev** [comment] 2016-07-21 15:11
@ig-ealbert I will just close this one. Once you're ready to pull all the translations in, you can just create a new issue!

**Closed** 2016-07-21 15:12 UTC
Labels: bug, mask-editor
