### ISSUE TITLE
Dates in datasource are reset to strings after the grouping of Date fields is removed

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/ignite-ui#1664] opened 2018-03-16 09:12 UTC
### Description  
Clearing the grouping of "date" fields causes the data source to reset date objects to string values.

### Steps to reproduce  

1. Open the attached sample. Datasource contains Date objects and the grid shows dates.
2. Group by DateAdded column.
3. Clear the grouping by pressing the X button on the group header.

### Result  
Datasource now contains string values instead of Dates. The grid shows string values instead of Dates.

### Expected result  
The datasource should preserve Date values. The grid should show Dates.

### Attachments  
[flatgrid.zip](https://github.com/IgniteUI/ignite-ui/files/1818593/flatgrid.zip)

**Comment by MayaKirova** [comment] 2018-03-19 09:28
The issue is actually with the grid, more specifically the autoGenerateColumns option.
As such the fix will be in the git tfs repo.

**Closed** 2018-11-21 14:31 UTC
Labels: bug, grid, status: verified, version: 18.1
