### ISSUE TITLE
[igDatePicker]Entered date is converted to today's date when pressing the Enter key

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/ignite-ui#1453] opened 2017-12-18 13:57 UTC
### Description  
Entered date is converted to today's date when pressing the Enter key

### Steps to reproduce  

1. Open attached sample (editor.htm)
2. Open igDatePicker's dropdown
5. Click in the igDatePicker's input area
6. Enter a date different from today's date
7. Press the "Enter" key

### Result  
The date is converted to today's date

### Expected result  
The entered date should be kept.

### Attachments  
[editor.zip](https://github.com/IgniteUI/ignite-ui/files/1568115/editor.zip)

**Comment by damyanpetev** [comment] 2017-12-19 15:06
Since the picker is open and without a value it will have today's date selected indeed, so hitting enter is technically selecting the right thing...

The real issue is with `dateInputFormat` which is not compatible with the jQuery UI `datepicker` formatting, so it can't parse the input and we lose the auto-update feature. The latter would normally have the calendar move to the date typed and then hitting enter triggers a selection on the correct value.
This can be easily verified/worked around by setting the `datepicker` format to match (specific to this case): 
```js
$("#editor1").igDatePicker({
  dateInputFormat: "dd-MMM-yyyy",
  datepickerOptions: {
    dateFormat: "dd-mm-yy"
  }
});
```

Mixing typing with opening the calendar (rather than selection via mouse/keyboard shortcuts) is a bit of an edge case, however, since it works in some cases out of the box I tend to agree we can look into supporting this in more cases  - enhancement. //CC @SlavUI  

Because tokens are not a 1:1 match, I don't think that's a usable generic mapping or something we can bake into the control. Will be looking to patch the functionality with the picker APIs instead.

**Comment by damyanpetev** [comment] 2017-12-19 15:15
There's another version of "today reset" I landed on by misreading the steps:
1 .Open attached sample (editor.htm)
2. Open the dropdown
3. Use `CTLR` + arrows shortcuts to navigate to a different date
4. Press the "Enter" key

Seems to be caused by a [double processing bug](https://bugs.jqueryui.com/ticket/10537) in the jQuery UI datepicker (still an issue in latest release 1.12.1, despite the comment).
Because of the `dateInputFormat` on our control we set/get calendar values via API on open/select respectively.
However, the double selection on the picker causes a parse attempt on the selected text after our formatting, which fails and returns the default date (today) instead.

**Closed** 2017-12-20 09:37 UTC
Labels: bug, datepicker, enhancement, status: in-development, version: 17.1, version: 17.2, version: 18.1
