### ISSUE TITLE
Clear button is shown on editors when they are disabled

### ISSUE THREAD

**Issue by TammyD79** [IgniteUI/ignite-ui#643] opened 2016-12-12 11:56 UTC
Previously the clear button was hidden on the editors when they were disabled. With the re-written controls it is now shown which gives the interpretation that the field is editable. Can the shipped version of the control be updated to hide the button when its disabled?

**Comment by IG-Stanimir-Dimitrov** [comment] 2016-12-12 15:07
@TammyD79 , we have decoupled the editor logic from its configuration. By design it currently could be disable and still display its button type.

Is there a particular case where you absolutely need to hide the button when the editor is disabled?

**Comment by TammyD79** [comment] 2016-12-12 15:45
From a user experience perspective it just gives the impression to the user that it's an editable field. The button is still interactive even though it's disabled.

**Comment by kdinev** [comment] 2016-12-12 16:04
@StefanIvanov I checked the spec and nothing is specified for the clear button behavior, except that it should always be the right-most button on the editor. Can we get an update on how it should behave in empty/readonly/disabled states? I think it was already updated to not show in empty state.

**Comment by IG-Stanimir-Dimitrov** [comment] 2016-12-12 16:13
@TammyD79 , the disabled editor is greyed out by default indicating to the end user that it is not editable. All buttons are also non-interactive when the editor is disabled as per the API reference.

If you experience a case where the editor is disabled, but you still can interact with the button and change values, please submit a new issue for a potential bug.

**Comment by TammyD79** [comment] 2016-12-12 16:16
If you click on it with the mouse it gets a blue focus around the button.

**Comment by TammyD79** [comment] 2016-12-12 20:52
I guess that's a result of our re-styling. For us where this comes in is we don't want the box completely gray when it's disabled. We have a CRUD screen and we want the user to be able to read the contents. Previously before upgrading this button was hidden and it made sense. What are the limitations from doing this here? It seems similar to having it hidden when there is not text in the control in my opinion.

**Comment by IG-Stanimir-Dimitrov** [comment] 2016-12-13 14:17
@TammyD79 If you are already re-styling, you can always hide the clear button in CSS like this
```
#<editor id>_clearButton {
      display: none;
  }
```
In future we may also change the default behavior after assessing all needs and best UX practices.

**Comment by TammyD79** [comment] 2016-12-13 19:44
I tweaked some css.

**Comment by IG-Stanimir-Dimitrov** [comment] 2016-12-19 17:31
To close this topic, as per the specification, the default editors behavior currently is as follows:

- the clear button is always present when enabled, even when the editors are empty (which is different from the standard HTML5 input search type elements)
- the clear button is always displayed, even when the editors are disabled
- the clear button is rendered from left to right
- if more than one button is enabled in the editors (clear, spinner & dropdown), the clear button is the left most one
- when right to left style is applied, the buttons (incl. clear) as mirrored on the left side
- when the editors are disabled, the clear button is non-interactive

**Closed by IG-Stanimir-Dimitrov** 2016-12-19 17:31 UTC
Labels: editors, status: by-design
