### ISSUE TITLE
Suppres keyboard showing when multipleSelection is used

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#448] opened 2016-10-24 14:29 UTC
**Client requirement**
Not focus the combo and have the keyboard pop up on touch devices when the SuppressKeyboard flag is on to allow the user to keep tapping all the options

**Comment by kdinev** [comment] 2016-10-24 14:46
Duplicate of #284 
Already done.

**Comment by zdrawku** [comment] 2016-10-25 12:21
When suppressKeyboard flag is on along with multipleSelection, the focus should not move to the combo input in order keyboard to remain hidden while choosing different items from the dropdown list.

**Closed** 2016-10-28 10:27 UTC
Labels: combo, enhancement
