### ISSUE TITLE
[Treegrid] Filter dropdown text distortion

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/ignite-ui#1373] opened 2017-11-08 08:54 UTC
### Description  
Filter dropdown text distortion

### Steps to reproduce  

1. Open the attached sample
2. Open the filter dropdown

### Result  
The filter items are badly misaligned. Happens in Japanese.

### Expected result  
The text looks normal

### Attachments  

[index.zip](https://github.com/IgniteUI/ignite-ui/files/1453157/index.zip)

https://www.screencast.com/t/eV3EYASQeB

**Comment by mpavlinov** [comment] 2017-11-09 08:32
@EmilTanev The issue is fixed in the samples. We will also apply a fix in the product, that's why I'll keep this issue open.

**Closed** 2017-11-29 10:09 UTC
Labels: bug, severity: medium, status: resolved, tree-grid, version: 17.2, version: 18.1
