### ISSUE TITLE
If combo has larger itemTemplate the content is cut off.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/ignite-ui#2198] opened 2022-06-02 15:05 UTC
## Description  
Custom content is cut off to the size of the default combo items.

 * ignite-ui version: 
 * browser: 

## Steps to reproduce  

1. Run this sample:
[test.zip](https://github.com/IgniteUI/ignite-ui/files/8825103/test.zip)

2. Open the combo and observe it:
![image](https://user-images.githubusercontent.com/10397980/171660072-145f2d42-a580-4e67-b9b7-bb09fa23e5bf.png)

## Result  
Content within the item is cut off.

## Expected result  
Content is visible.

Note that this is the same sample as in the samples: https://www.igniteui.com/combo/templates
The samples currently use version 21.1.11 and it seems to work as expected there.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by hanastasov** [comment] 2022-06-21 08:51
Duplicate of https://github.com/IgniteUI/ignite-ui/issues/2174

**Closed** 2022-07-20 10:54 UTC
Labels: bug, combo, regression, status: resolved
